name: Auto Update KMB and CTB Database

on:
  schedule:
    - cron: '0 20 * * *' # 國際標準時間 20:00 = 香港時間凌晨 4:00 自動運行
  workflow_dispatch: # 容許你隨時手動撳掣更新

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Python Scraper
      run: python update_data.py

    - name: Commit and Push if changed
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add kmb_rs.csv kmb_stop.csv ctb_rs.csv ctb_stop.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-updated DB by robot" && git push)
